blueprint:
  name: APP应用短信通知
  description: "模板内包含变量  短信消息：{{text}}，发送号码：{{from}}"
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha_app/blob/main/blueprints/ha_app_sms.yaml
  input:
    sensor_id:
      name: Android短信
      description: 家庭助理APP短信转发
      selector:
        entity:
          integration: mobile_app
          domain: sensor
          device_class: timestamp
    custom_action:
      name: 所有消息
      description: 收到短信时，执行此服务
      default: 
        - service: notify.persistent_notification
          data:
            message: 内容：{{text}}
            title: 号码：{{from}}
      selector:
        action: {}
    sgcc_code:
      name: 网上国网验证码
      description: 验证码信息
      default: []
      selector:
        action: {}
    express:
      name: 快递消息
      description: 菜鸟驿站、兔喜生活、快递超市、百世快递、微快递、申通快递、菜鸟智能柜
      default: []
      selector:
        action: {}
    captcha:
      name: 验证码
      description: 验证码
      default: []
      selector:
        action: {}
    bank:
      name: 银行
      description: 交通银行、招商银行、农业银行、光大银行、建设银行、网商银行、工商银行、平安银行、微众银行、广发银行、湖北农信
      default: []
      selector:
        action: {}
trigger:
- platform: state
  entity_id: !input sensor_id
action:
- variables:
    text: '{{ trigger.to_state.attributes.content }}'
    from: '{{ trigger.to_state.attributes.from }}'
- choose:
  - conditions:
    - '{{ "网上国网验证码" in text }}'
    sequence: !input sgcc_code
  - conditions:
    - '{{ "菜鸟驿站" in text }}'
    - '{{ "兔喜生活" in text }}'
    - '{{ "快递超市" in text }}'
    - '{{ "百世快递" in text }}'
    - '{{ "微快递" in text }}'
    - '{{ "申通快递" in text }}'
    - '{{ "菜鸟智能柜" in text }}'
    sequence: !input express
  - conditions:
    - '{{ "验证码" in text }}'
    sequence: !input captcha
  - conditions:
    - '{{ "交通银行" in text }}'
    - '{{ "招商银行" in text }}'
    - '{{ "农业银行" in text }}'
    - '{{ "光大银行" in text }}'
    - '{{ "建设银行" in text }}'
    - '{{ "网商银行" in text }}'
    - '{{ "工商银行" in text }}'
    - '{{ "平安银行" in text }}'
    - '{{ "微众银行" in text }}'
    - '{{ "广发银行" in text }}'
    - '{{ "湖北农信" in text }}'
    sequence: !input bank
- service: script.turn_on
  target:
    entity_id: !input custom_action