blueprint:
  name: APP应用通知消息
  description: "模板内包含变量  标题：{{title}}  内容：{{content}}  短文本：{{text}}  应用包：{{package}}"
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha_app/blob/main/blueprints/ha_app_notify.yaml
  input:
    sensor_id:
      name: 'Android 通知'
      description: 家庭助理APP通知转发      
      selector:
        entity:
          integration: mobile_app
          domain: sensor
          device_class: timestamp
    custom_action:
      name: 所有应用
      description: 接收到应用通知消息时，执行此服务
      default: 
        - service: notify.persistent_notification
          data:
            message: |
                内容：{{content}}
                短文本：{{text}}  
                应用包：{{package}}
            title: "{{title}}"
      selector:
        action: {}
    com_xiaomi_smarthome:
      name: 米家
      description: com.xiaomi.smarthome
      default: []
      selector:
        action: {}
    com_tencent_mm:
      name: 微信
      description: com.tencent.mm
      default: []
      selector:
        action: {}
    com_tencent_mobileqq:
      name: QQ
      description: com.tencent.mobileqq
      default: []
      selector:
        action: {}
    com_coolkit:
      name: 易微联
      description: com.coolkit
      default: []
      selector:
        action: {}
    com_byd_aeri_caranywhere:
      name: 比亚迪
      description: com.byd.aeri.caranywhere
      default: []
      selector:
        action: {}
trigger:
- platform: state
  entity_id: !input sensor_id
action:
- variables:
    package: '{{ trigger.to_state.attributes.package }}'
    title: '{{ trigger.to_state.attributes.title }}'
    content: '{{ trigger.to_state.attributes.content }}'
    text: '{{ trigger.to_state.attributes.text }}'
- choose:
  - conditions:
    - '{{ package == "com.xiaomi.smarthome" }}'
    sequence: !input com_xiaomi_smarthome
  - conditions:
    - '{{ package == "com.tencent.mm" }}'
    sequence: !input com_tencent_mm
  - conditions:
    - '{{ package == "com.tencent.mobileqq" }}'
    sequence: !input com_tencent_mobileqq
  - conditions:
    - '{{ package == "com.coolkit" }}'
    sequence: !input com_coolkit
  - conditions:
    - '{{ package == "com.byd.aeri.caranywhere" }}'
    sequence: !input com_byd_aeri_caranywhere
- choose:
  - conditions: []
    sequence: !input custom_action
