blueprint:
  name: APP应用按钮点击事件
  description: "点击通知栏的按钮自定义服务，上👆下👇左👈右👉OK👌"
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha_app/blob/main/blueprints/ha_app_button.yaml
  input:
    sensor_id:
      name: 按钮事件
      description: 家庭助理APP点击预设按钮触发自动化
      selector:
        entity:
          integration: mobile_app
          domain: sensor
          device_class: timestamp
    up:
      name: 👆
      description: 上
      default: []
      selector:
        action: {}
    down:
      name: 👇
      description: 下
      default: []
      selector:
        action: {}
    left:
      name: 👈
      description: 左
      default: []
      selector:
        action: {}
    right:
      name: 👉
      description: 右
      default: []
      selector:
        action: {}
    ok:
      name: 👌
      description: OK
      default: []
      selector:
        action: {}
    volume_up:
      name: 🔊
      description: 音量+
      default: []
      selector:
        action: {}
    volume_down:
      name: 🔈
      description: 音量-
      default: []
      selector:
        action: {}
    miband_play:
      name: ▶️
      description: 小米手环 - 播放
      default: []
      selector:
        action: {}
    miband_pause:
      name: ⏸️
      description: 小米手环 - 暂停
      default: []
      selector:
        action: {}
    miband_prev:
      name: ⏮️
      description: 小米手环 - 上一个
      default: []
      selector:
        action: {}
    miband_next:
      name: ⏭️
      description: 小米手环 - 下一个
      default: []
      selector:
        action: {}
    miband_volume_up:
      name: 🔊
      description: 小米手环 - 增加音量
      default: []
      selector:
        action: {}
    miband_volume_down:
      name: 🔉
      description: 小米手环 - 降低音量
      default: []
      selector:
        action: {}
trigger:
- platform: state
  entity_id: !input sensor_id
action:
- variables:
    data: '{{ trigger.to_state.attributes.key }}'
- choose:
  - conditions:
    - '{{ data == "up" }}'
    sequence: !input up
  - conditions:
    - '{{ data == "down" }}'
    sequence: !input down
  - conditions:
    - '{{ data == "left" }}'
    sequence: !input left
  - conditions:
    - '{{ data == "right" }}'
    sequence: !input right
  - conditions:
    - '{{ data == "ok" }}'
    sequence: !input ok
  - conditions:
    - '{{ data == "volume_up" }}'
    sequence: !input volume_up
  - conditions:
    - '{{ data == "volume_down" }}'
    sequence: !input volume_down
  - conditions:
    - '{{ data == "miband_play" }}'
    sequence: !input miband_play
  - conditions:
    - '{{ data == "miband_pause" }}'
    sequence: !input miband_pause
  - conditions:
    - '{{ data == "miband_prev" }}'
    sequence: !input miband_prev
  - conditions:
    - '{{ data == "miband_next" }}'
    sequence: !input miband_next
  - conditions:
    - '{{ data == "miband_volume_up" }}'
    sequence: !input miband_volume_up
  - conditions:
    - '{{ data == "miband_volume_down" }}'
    sequence: !input miband_volume_down